import { describe, it, expect } from "vitest";
import catalog from "../src/catalog.json" with { type: "json" };

// Guards against a catalog generated by an older generator landing on main
// (e.g. a stale weekly update-catalog PR merged after the generator changed).
// An unresolved $ref is a dangling pointer the LLM cannot follow, because the
// catalog does not ship the spec's components section.
describe("catalog.json", () => {
  it("contains no unresolved $ref", () => {
    const offenders = catalog
      .filter((entry) => JSON.stringify(entry).includes('"$ref"'))
      .map((entry) => entry.id);
    expect(offenders).toEqual([]);
  });

  it("has unique action IDs", () => {
    const ids = catalog.map((entry) => entry.id);
    expect(new Set(ids).size).toBe(ids.length);
  });
});
